 version: "3.8"

 services:
   portal-app:
     build:
       context: .
       dockerfile: Dockerfile
     container_name: portal-app
     restart: unless-stopped
     environment:
       NODE_ENV: production
       VITE_API_URL: https://app.para.autos
     networks:
       - portal_network
       - proxy-net
 networks:
  portal_network:
   driver: bridge
  proxy-net:
     external: true
