export const queryKeys = {
  projects: ['projects'] as const,
  projectDetail: (id: string) => ['projects', id] as const,
  projectBrief: (id: string) => ['projects', id, 'brief'] as const,
  tasks: ['tasks'] as const,
  tasksByProject: (projectId: string) => ['tasks', 'project', projectId] as const,
  sessions: ['sessions'] as const,
  sessionsByProject: (projectId: string) => ['sessions', 'project', projectId] as const,
  progress: ['progress'] as const,
  progressByTask: (taskId: string) => ['progress', 'task', taskId] as const,
  timeBlocks: ['timeBlocks'] as const,
  timeBlocksByDate: (date: string) => ['timeBlocks', 'date', date] as const,
  milestones: ['milestones'] as const,
  milestonesByProject: (projectId: string) => ['milestones', 'project', projectId] as const,
  risks: ['risks'] as const,
  risksByProject: (projectId: string) => ['risks', 'project', projectId] as const,
  decisions: ['decisions'] as const,
  decisionsByProject: (projectId: string) => ['decisions', 'project', projectId] as const,
  achievements: ['achievements'] as const,
  achievementsByProject: (projectId: string) => ['achievements', 'project', projectId] as const,
} as const;
